### ISSUE TITLE
Specify Playlist

### ISSUE THREAD

**Issue by jdcauley** [bfncs/jQuery-Youtube-Channel-Player#3]
Any quick way to specify a playlist.

**Comment by bfncs** [comment]
Hi there,

this is a great idea, but since it needs another Youtube API call (not only changing a parameter) and this Plugin is in the first place suited to play Youtube _channels_ (hence the name), I'm not keen on implementing it myself at the moment. Maybe this will be possible later on.

If you could add it in yourself, I would be grateful and add it to plugin for sure.

To get you going, have a look at the corresponding sections in the Google API docs:
- [Developer Guide about Playlists](https://developers.google.com/youtube/2.0/developers_guide_protocol#Playlists)
- [Developer Reference for Playlist feeds](https://developers.google.com/youtube/2.0/reference#Playlists_Feeds)
