### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by lightoflifeministry** [bfncs/jQuery-Youtube-Channel-Player#4]
yesterday it was working pretty well but today i'm getting No Results only....whyyyyy?

**Comment by bfncs** [comment]
Thanks a lot for reporting the issue. I'm also experiencing this kind of problems since today.

The plugin is based on the [Youtube API v2.0](https://developers.google.com/youtube/2.0/developers_guide_protocol) which has been deprecated since March 4, 2014. I'm afraid that this part of the API has been deactivated since today, though it's strange because the request doesn't throw an error but just brings up an empty result.

What is definitely needed in the next time is porting the API to use [Youtube API v3.0](https://developers.google.com/youtube/v3/) requests, but it might take me some time for me to implement it.

**Comment by lightoflifeministry** [comment]
thanks for the quick response ... hope to fix it soon.

**Comment by lightoflifeministry** [comment]
it works fine now .
thank you.

**Comment by bfncs** [comment]
Well, then this was just a temporary outage of the Youtube API. Still I'm planning to get the Plugin ported to API v3.0 as quickly as possible.
